name: Sync to Org

on:
  push:
    branches:
      - main

jobs:
  sync_to_org:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Organization
        env:
          TOKEN: ${{ secrets.ORG_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git remote add org-repo https://x-access-token:${TOKEN}@github.com/BF-D-challenge/make-own-product1.git
          git push org-repo HEAD:main --force
