name: Sync to Org

on:
  push:
    branches: [ "main" ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Organization Repository
        env:
          ORG_TOKEN: ${{ secrets.ORG_TOKEN }}
        run: |
          git remote add org "https://jhlee3663-netizen:${ORG_TOKEN}@github.com/BF-D-challenge/make-own-product1.git"
          git push org main -f
